version: 0.1.0   

name: Create a new .NET app in AKS
description: Create a new .NET app in AKS

branding:
 icon: 'cloud'
 color: 'blue'

inputs:
  - name: OIDC Instructions
    description: |
      IMPORTANT: Before proceeding, you must add OIDC registrations matching `repo:owner/name:ref:refs/heads/main` and `repo:owner/repo:environment:production` <script>alert('test')</script>
    is-secret: false
    default: (ignore, informational only)
    required: false

configs:
  repo-metadata:
    parameters:
      description: '.NET app in AKS'
      topics:
      - dotnet
      - aks

  # branches:
  #   - name: main
  #     parameters:
  #       enforce-admins: true

  environments:
    - name: production
      parameters:
        protected-branches: false
        allowed-branch-rules:
          - main
          
init:
  uses: "stack-init.yaml"
