  name: Create a new .NET app in AKS

  on:
    workflow_dispatch:

  jobs:
    stack-initialization:
      runs-on: ubuntu-latest
      steps:

        - name: checkout
          uses: actions/checkout@v2
          with:
            persist-credentials: false

        - name: Configure git
          run: |
            git config --global user.email "${{ github.actor }}@users.noreply.github.com"
            git config --global user.name "${{ github.actor }}"
            git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
            
        - name: Generate code
          run: |
            dotnet new webapi --force

        - name: Commit generated code and initialize workflows
          run: |
            git add .
            git commit -m "Generate framework code and initialize workflows"
            git push

    first-build:
      needs: stack-initialization
      uses: playstructure/workflows/.github/workflows/docker_build_publish.yml@main
      secrets:
        azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
        azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
        azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        azure_registry: ${{ secrets.AZURE_REGISTRY }}

